### ISSUE TITLE
Асинхронный сокет

### ISSUE THREAD

**Issue by Troxid** [sensorika/sensorika-robot-rust#4]
В трейт `util::sendrecvjson::SendRecvJson` необходимо добавить асинхронные версии методов recv\send или создать отдельный трейт с асинхр. методами.
Реализовать эти треты для `zmq::Socket` с помощью флага _DONTWAIT_

``` rust
socket.recv_msg(DONTWAIT)
```

**Comment by asmfreak** [comment]
Поправлено в bc5793631be82ad25a8476f2bc785a3deb01a13e и c96f303d27b28a9cc894f414ba27a38f53b3fe5c

**Comment by kkirsanov** [comment]
Это кошмарнее делать через пуллеры - http://api.zeromq.org/3-2:zmq-poll

Я в питонячем коде так переделал.

**Comment by asmfreak** [comment]
> Это кошмарнее делать через пуллеры - http://api.zeromq.org/3-2:zmq-poll
> Я в питонячем коде так переделал.

У сокета в rust-zmq у сокета poll есть метод. чрезвычайно удобно.
